# Generated by Django 5.0.4 on 2024-04-16 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scibilityapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidadesprojeto',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scibilityapi.projetos'),
        ),
        migrations.AlterField(
            model_name='habilidadesusuario',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scibilityapi.usuario'),
        ),
    ]
