# Generated by Django 5.0.4 on 2024-04-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scibilityapi', '0002_alter_habilidadesprojeto_projeto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessados', to='scibilityapi.projetos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses', to='scibilityapi.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'projeto')},
            },
        ),
    ]
