# Generated by Django 5.0.4 on 2024-04-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scibilityapi', '0003_interesseprojeto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interesseprojeto',
            table='interesse_projeto',
        ),
    ]
